# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-06 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20191006_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='category',
            new_name='image_category',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='location',
            new_name='image_location',
        ),
    ]
