# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20191006_1953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
