# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20191007_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_category',
            new_name='category',
        ),
    ]
